/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gh_tool_CppExample */

#ifndef _Included_com_gh_tool_CppExample
#define _Included_com_gh_tool_CppExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gh_tool_CppExample
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gh_tool_CppExample_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
